# kubectl run web --image=nginx --port=80
kind: Pod
apiVersion: v1
metadata: 
  name: web
  namespace: testbed-ns
spec:
  containers:
    - name: nginx
      image:  nginx
      ports:
        - containerPort: 80
#          protocols: TCP       # UDP 일때는 사용해야 한다.
